/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(Compiler p, int id) {
    super(p, id);
  }

  @Override
  public int process(String className) {
    SimpleNode left = (SimpleNode)this.children[0];
    SimpleNode right = (SimpleNode)this.children[1];
    // int left_val;
    // int right_val;
    left.process(className);
    right.process(className);

    if (!left.getType().equals(Symbol.BOOLEAN) || !right.getType().equals(Symbol.BOOLEAN)){
      throw new RuntimeException("ASTAnd is not a Boolean"+ "\nLine: " + this.line + "; Col: " + this.column);
    }
    
    return 1;
  }


  public String getType(){
    return Symbol.BOOLEAN;
  }

  public String generateCode(String className){
    // System.out.println("CodeGenerator " + this.getClass() + " : SIMPLENODE");
    String code = "";
    if (this.children != null)
      for(int i = 0; i < this.children.length; i++) {
        code += ((SimpleNode)this.children[i]).generateCode(className);
      }

    code += "iand\n";

    CodeGenerator.decStack(1);

    return code;
  }

}
/* JavaCC - OriginalChecksum=ed084117f04b5765ad1446a1a0ce70a2 (do not edit this line) */
