/* Generated By:JJTree: Do not edit this line. ASTAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
  }

  public ASTAnd(Compiler p, int id) {
    super(p, id);
  }

  @Override
  public int process() {
    //SimpleNode left = (SimpleNode)this.children[0];
    //SimpleNode right = (SimpleNode)this.children[1];
    int left_val;
    int right_val;

    if(this.children[0].getClass().equals(ASTIdentifier.class)) {
      ASTIdentifier left = (ASTIdentifier)this.children[0];
      if (SemanticProcessor.types_table.get(left.ast_value) == null)
        throw new RuntimeException("Variable in ASTAnd not previous declared");
      // left = ()
      if (SemanticProcessor.types_table.get(left.ast_value) == "boolean")
        left_val = SemanticProcessor.values_table.get(left.ast_value);
      else
        throw new RuntimeException("Left child (" + left.ast_value + ") in ASTAnd is not an Boolean");
    }
    else {
      SimpleNode left = (SimpleNode)this.children[0];
      left_val = left.process();
    }

    if(this.children[1].getClass().equals(ASTIdentifier.class)) {
      ASTIdentifier right = (ASTIdentifier)this.children[1];
      if (SemanticProcessor.types_table.get(right.ast_value) == "boolean")
        right_val = SemanticProcessor.values_table.get(right.ast_value);
      else
        throw new RuntimeException("Right child (" + right.ast_value + ") in ASTAnd is not an Boolean");
    }
    else{
      SimpleNode right = (SimpleNode)this.children[1];
      right_val = right.process();
    } 
    
    if(left_val == 1 && 1 == right_val) return 1;
    else return 0;
  }

}
/* JavaCC - OriginalChecksum=ed084117f04b5765ad1446a1a0ce70a2 (do not edit this line) */
