/* Generated By:JJTree: Do not edit this line. ASTBool.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBool extends SimpleNode {
  public boolean ast_value;

  public ASTBool(int id) {
    super(id);
  }

  public ASTBool(Compiler p, int id) {
    super(p, id);
  }

  @Override
  public int process() {
    if(ast_value) return 1;
    return 0;
  }

  public String getNodeType() {
    return this.getClass().toString();
  }

}
/* JavaCC - OriginalChecksum=e2d69096d5c57c4b88fb9ebba8f767ec (do not edit this line) */
