/* Generated By:JJTree: Do not edit this line. ASTImportArg.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportArg extends SimpleNode {
  String ast_type;

  public ASTImportArg(int id) {
    super(id);
  }

  public ASTImportArg(Compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bf21f5c25b722f194e5efe132a36056d (do not edit this line) */
