/* Generated By:JJTree: Do not edit this line. ASTImportArgs.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportArgs extends SimpleNode {
  public ASTImportArgs(int id) {
    super(id);
  }

  public ASTImportArgs(Compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5f23644fe8793aa039fa6e692805823 (do not edit this line) */
