/* Generated By:JJTree: Do not edit this line. ASTLess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLess extends SimpleNode {
  public ASTLess(int id) {
    super(id);
  }

  public ASTLess(Compiler p, int id) {
    super(p, id);
  }

  
  @Override
  public int process(String className) {


    SimpleNode left = (SimpleNode)this.children[0];
    SimpleNode right = (SimpleNode)this.children[1];
    // int left_val;
    // int right_val;
    left.process(className);
    right.process(className);

    if (!left.getType().equals(Symbol.INT) || !right.getType().equals(Symbol.INT)){
      throw new RuntimeException("ASTLess is not a Integer" + "\nLine: " + this.line + "; Col: " + this.column);
    }
    
    return 1;
  }

  public String getType(){
    return Symbol.BOOLEAN;
  }

}
/* JavaCC - OriginalChecksum=55151cda9b74838fc120e731d3367712 (do not edit this line) */
