/* Generated By:JJTree: Do not edit this line. ASTLength.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLength extends SimpleNode {
  public ASTLength(int id) {
    super(id);
  }

  public ASTLength(Compiler p, int id) {
    super(p, id);
  }

 
  @Override
  public int process(String className) {
    System.out.println(this.getClass());
    
    SimpleNode bro = (SimpleNode)(((SimpleNode)this.jjtGetParent()).children[0]);



    if(bro instanceof ASTIdentifier) {
      Symbol symb = getSymbolFromTable(((ASTIdentifier)bro).ast_value);
      if(!symb.type.equals(Symbol.INT_ARRAY)){
        throw new RuntimeException(((ASTIdentifier)bro).ast_value + " is not a array (length check)");
      }
    } else if (bro instanceof ASTAcessMethod){
      ASTAcessMethod broo = ((ASTAcessMethod) bro);
      if(!broo.returnType.equals(Symbol.INT_ARRAY)){
        throw new RuntimeException(broo.ast_method + " doesn't return a array (length check) returns " + broo.returnType);
      }
    }


    return 1;
  }

  public String getType(){
    return Symbol.INT;
  }

}
/* JavaCC - OriginalChecksum=355dc3240ae72e2bab32488505528258 (do not edit this line) */
