/* Generated By:JJTree: Do not edit this line. ASTLess.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLess extends SimpleNode {
  public ASTLess(int id) {
    super(id);
  }

  public ASTLess(Compiler p, int id) {
    super(p, id);
  }

  
  @Override
  public int process() {
    System.out.println(this.getClass());
    if (this.children == null) return 1;
    for(int i = 0; i < this.children.length; i++) {
      ((SimpleNode)this.children[i]).process();
    }
    return 1;
  }


}
/* JavaCC - OriginalChecksum=55151cda9b74838fc120e731d3367712 (do not edit this line) */
