/* Generated By:JJTree: Do not edit this line. ASTMain.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMain extends SimpleNode {
  public ASTMain(int id) {
    super(id);
  }

  public ASTMain(Compiler p, int id) {
    super(p, id);
  }

  @Override
  public int process() {
    SemanticProcessor.insideMethod = true;
    
    SimpleNode curr_node;
    for (int i = 0; i < this.children.length; i++) {
      curr_node = (SimpleNode)this.children[i];
      curr_node.process();
    }

    SemanticProcessor.insideMethod = false;

    return 1;
  }

}
/* JavaCC - OriginalChecksum=58f127b3047114438a993e42197cc3f7 (do not edit this line) */
