/* Generated By:JJTree: Do not edit this line. ASTMethod.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
import java.util.List;

public
class ASTMethod extends SimpleNode {
  public String ast_id;
  public String ast_type ;

  public ASTMethod(int id) {
    super(id);
  }

  public ASTMethod(Compiler p, int id) {
    super(p, id);
  }

  @Override
  public int process() {//TODO: ir buscar os argumentos aos fihos
    List<String> arroz;
    SimpleNode curr_node;
    for (int i = 2; i < this.children.length; i++) {
      curr_node = this.children[i];
      
    }
    SemanticProcessor.methods_table.put(ast_id, new SymbolMethod(ast_id, arroz, ast_type));*/
    return 1;
  }
  
}
/* JavaCC - OriginalChecksum=dee4677a4569967c602fa79e0250dbf5 (do not edit this line) */
