/* Generated By:JJTree: Do not edit this line. ASTNeg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNeg extends SimpleNode {
  public ASTNeg(int id) {
    super(id);
  }

  public ASTNeg(Compiler p, int id) {
    super(p, id);
  }

 
  
  @Override
  public int process(String className) {

    SimpleNode child = (SimpleNode)this.children[0];
    // int left_val;
    // int right_val;
    child.process(className);

    if (child.getType().equals(Symbol.BOOLEAN)){
      throw new RuntimeException("ASTNeg is not a Boolean");
    }
    
    return 1;

    // SimpleNode child = (SimpleNode)this.children[0];
    // int child_return = child.process(className);

    // if(child_return != 0 && child_return != 1) {
    //     throw new RuntimeException("Não podes negar numeros, isso só o afonso é que pode");
    // }
    // else return child_return^1;
  }

  public String getType(){
    return Symbol.BOOLEAN;
  }
}
/* JavaCC - OriginalChecksum=e2edacf504bf837f510ac7c133d6a866 (do not edit this line) */
