/* Generated By:JJTree: Do not edit this line. ASTProgram.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTProgram extends SimpleNode {
  
  public ASTProgram(int id) {
    super(id);
  }

  public ASTProgram(Compiler p, int id) {
    super(p, id);
  }

 
  @Override
  public int process(String className) {
    System.out.println(this.getClass());
    if (this.children == null) return 1;
    for(int i = 0; i < this.children.length; i++) {
      ((SimpleNode)this.children[i]).process(className);
    }
    return 1;
  }

  // public String getNodeType() {
  //   return this.getClass().toString();
  // }

}
/* JavaCC - OriginalChecksum=0ff3fb6d727a39b95630f7e0f8f0ca41 (do not edit this line) */
