/* Generated By:JJTree: Do not edit this line. ASTGroupCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGroupCondition extends SimpleNode {
  public ASTGroupCondition(int id) {
    super(id);
  }

  public ASTGroupCondition(Compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=222f506a4c1c7a3b91484b46866c563e (do not edit this line) */
