/* Generated By:JJTree: Do not edit this line. ASTImports.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImports extends SimpleNode {
  public ASTImports(int id) {
    super(id);
  }

  public ASTImports(Compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=98d5cf4c9fa523da1567a8049ec874e9 (do not edit this line) */
