/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportDeclaration extends SimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(Compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=86993ffe1259d54573d5e2a8c410b5ae (do not edit this line) */
