/* Generated By:JJTree: Do not edit this line. ASTMethodArgs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMethodArgs extends SimpleNode {
  public ASTMethodArgs(int id) {
    super(id);
  }

  public ASTMethodArgs(Compiler p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b6ff4d6b573e735e7e85760ac5e431bc (do not edit this line) */
