/* Generated By:JavaCC: Do not edit this line. CompilerTreeConstants.java Version 5.0 */
public interface CompilerTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTFILE = 2;
  public int JJTIFELSE = 3;
  public int JJTWHILE = 4;
  public int JJTASSIGN = 5;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "File",
    "IfElse",
    "While",
    "Assign",
  };
}
/* JavaCC - OriginalChecksum=a2d184176448846095f8c3446c39080b (do not edit this line) */
