/* Generated By:JJTree&JavaCC: Do not edit this line. CompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 5;
  /** RegularExpression Id. */
  int LF = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int NEW = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int MAIN = 13;
  /** RegularExpression Id. */
  int THIS = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int CLASS = 17;
  /** RegularExpression Id. */
  int PUBLIC = 18;
  /** RegularExpression Id. */
  int STATIC = 19;
  /** RegularExpression Id. */
  int STRING = 20;
  /** RegularExpression Id. */
  int LENGTH = 21;
  /** RegularExpression Id. */
  int RETURN = 22;
  /** RegularExpression Id. */
  int BOOLEAN = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int IMPORT = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"   \"",
    "<INTEGER>",
    "\"\\n\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"void\"",
    "\"else\"",
    "\"true\"",
    "\"main\"",
    "\"this\"",
    "\"while\"",
    "\"false\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"String\"",
    "\"length\"",
    "\"return\"",
    "\"boolean\"",
    "\"extends\"",
    "\"import\"",
    "<IDENTIFIER>",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"!\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
  };

}
