/* Generated By:JavaCC: Do not edit this line. CompilerTreeConstants.java Version 5.0 */
public interface CompilerTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTSTART = 1;
  public int JJTFILE = 2;
  public int JJTIMPORTS = 3;
  public int JJTIMPORTDECLARATION = 4;
  public int JJTCLASSDECLARATION = 5;
  public int JJTVARDECLARATION = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTMETHODARGS = 8;
  public int JJTVOID = 9;
  public int JJTSTATEMENT = 10;
  public int JJTIF = 11;
  public int JJTELSE = 12;
  public int JJTIDENTIFIER = 13;
  public int JJTASSIGN = 14;
  public int JJTWHILESTATEMENT = 15;
  public int JJTAND = 16;
  public int JJTLESS = 17;
  public int JJTADD = 18;
  public int JJTSUB = 19;
  public int JJTMUL = 20;
  public int JJTDIV = 21;
  public int JJTINT = 22;
  public int JJTGROUPCONDITION = 23;
  public int JJTTRUE = 24;
  public int JJTFALSE = 25;
  public int JJTTHIS = 26;
  public int JJTARRAY = 27;
  public int JJTOBJECT = 28;
  public int JJTNEG = 29;
  public int JJTACESSARRAY = 30;
  public int JJTLENGTH = 31;
  public int JJTACESSMETHOD = 32;
  public int JJTARGUMENTS = 33;


  public String[] jjtNodeName = {
    "Program",
    "Start",
    "File",
    "Imports",
    "ImportDeclaration",
    "ClassDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "MethodArgs",
    "void",
    "Statement",
    "If",
    "Else",
    "Identifier",
    "Assign",
    "WhileStatement",
    "And",
    "Less",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "Int",
    "GroupCondition",
    "True",
    "False",
    "This",
    "Array",
    "Object",
    "Neg",
    "AcessArray",
    "Length",
    "AcessMethod",
    "Arguments",
  };
}
/* JavaCC - OriginalChecksum=e5089cb8e97236851465fe263597e4f0 (do not edit this line) */
