/* Generated By:JJTree&JavaCC: Do not edit this line. CompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int NEW = 12;
  /** RegularExpression Id. */
  int VOID = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int TRUE = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int THIS = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int FALSE = 19;
  /** RegularExpression Id. */
  int CLASS = 20;
  /** RegularExpression Id. */
  int PUBLIC = 21;
  /** RegularExpression Id. */
  int STATIC = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int LENGTH = 24;
  /** RegularExpression Id. */
  int RETURN = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int EXTENDS = 27;
  /** RegularExpression Id. */
  int IMPORT = 28;
  /** RegularExpression Id. */
  int IDENTIFIER = 29;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 8>",
    "<INTEGER>",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"void\"",
    "\"else\"",
    "\"true\"",
    "\"main\"",
    "\"this\"",
    "\"while\"",
    "\"false\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"String\"",
    "\"length\"",
    "\"return\"",
    "\"boolean\"",
    "\"extends\"",
    "\"import\"",
    "<IDENTIFIER>",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"!\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
  };

}
